name: unsure
description: >
  An easy to use probabilistic notation, and a package that can parse it
  and calculate with it.
version: 0.2.0
homepage: https://github.com/filiph/unsure

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  petitparser: ^5.0.0
  t_stats: ^3.0.0

dev_dependencies:
  args: ^2.3.0
  pedantic: ^1.8.0
  test: ^1.6.0

executables:
  unsure: unsure
